[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
bond_vault = "6XGwWjKTTkWD6JcJQXGUeDexJfrY3Nv2gM4yjJs5jSNi"

[provider]
cluster = "devnet"
wallet = "../.proofcast-signer.json"

[scripts]
test = "cargo test"

[hooks]
