import { loadFont as loadInter } from "@remotion/google-fonts/Inter";
import { loadFont as loadNewsreader } from "@remotion/google-fonts/Newsreader";
import { loadFont as loadJetBrains } from "@remotion/google-fonts/JetBrainsMono";

export const inter = loadInter().fontFamily;
export const serif = loadNewsreader().fontFamily;
export const mono = loadJetBrains().fontFamily;

// Mirrors the ProofCast web app palette.
export const C = {
  bg: "#0b0d0c",
  raise: "#111514",
  line: "#232a27",
  ink: "#f2f4f2",
  dim: "#9aa5a0",
  accent: "#34e59b",
  accentDim: "#1d8a5e",
  danger: "#f26d6d",
  amber: "#e5c069",
};

// Real devnet receipts generated by the live app (Memo v1, signer 8eDztt…iQ7p).
export const RECEIPTS = {
  signer: "8eDzttbc34bt3efkExfE5CjUMyJ8oxaVCQ1qihC8iQ7p",
  commit: "4nNt5NG9v1hprzWAv6ze29w2TzNQwghm5YyrGLGWfv7i5Zo22EQXRMQZ23KWdhTLAa7fuEcLriZAcUyqsJuxB2vh",
  reveal: "3UHnEuswxXVPsNebA4G8WjQHkXK18ZqfpuTzFX8TBTwtXyHB6VSB1bpPp8cG8BbCUsYbALFiBPkYUJbs3FHEegVX",
  grade: "4Q78y9pQRLqmNHvcPGJQo6kcvKqjVTnzcdykFyREpivRPSwXZSfss2aH6c2y14fJKNGJpjZ7XNJupX8aQ3YkeMQn",
  commitHash: "b8fb947eefc95265a1d0f7c93e2b4a71c6e0d84f3a927b15",
};
